import pandas as pd
std=pd.read_csv("apandas/Students.csv")
print(std[:5])
print("====================================")
print(std[3:])
print("======================================")
print(std[3:8])
print("======================================")
print(std[-7:-4])
print("=======================================")
print(std[::-1])
print("=========================================")
print(std[::2])