a=int(input("enter the integer value"))
e=str(input("enter the name velue"))
b=float(input("enter the float value"))
c=bool(input("enter the bool velue"))
d=complex(input("enter the complex value"))
print(type(a))
print(type(e))
print(type(b))
print(type(c))
print(type(d))
print(id(a))
print(id(e))
print(id(b))
print(id(c))
print(id(d))